version: '3.8'

services:
  app:
    build: ./
    command: sh -c "uvicorn app:app --reload --port=8000 --host=0.0.0.0"
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - .:/code

volumes:
  app:

